# Team Data
# Team: Player
SWEEPSTAKE = {
    "Croatia": "Oran",
    "Iran": "Oran",
    "Germany": "Oran",
    "Paraguay": "Oran",
    "South Korea": "Swati",
    "Norway": "Swati",
    "Jordan": "Swati",
    "Czechia": "Swati",
    "Ecuador": "Noah",
    "Colombia": "Noah",
    "Brazil": "Noah",
    "Bosnia-Herzegovina": "Noah",
    "Austria": "Aimee",
    "Egypt": "Aimee",
    "Netherlands": "Aimee",
    "Ghana": "Aimee",
    "Sweden": "Kush",
    "Qatar": "Kush",
    "Japan": "Kush",
    "Congo DR": "Kush",
    "United States": "Micky",
    "Ivory Coast": "Micky",
    "Iraq": "Micky",
    "Mexico": "Micky",
    "Belgium": "Mae",
    "Canada": "Mae",
    "Senegal": "Mae",
    "Morocco": "Mae",
    "Spain": "Aden",
    "Turkey": "Aden",
    "Tunisia": "Aden",
    "Uruguay": "Aden",
    "Haiti": "Mary",
    "Argentina": "Mary",
    "Saudi Arabia": "Mary",
    "Cape Verde Islands": "Mary",
    "Algeria": "Will",
    "Australia": "Will",
    "New Zealand": "Will",
    "Portugal": "Will",
    "Uzbekistan": "Joe",
    "England": "Joe",
    "France": "Joe",
    "South Africa": "Joe",
    "Curaçao": "Izzy",
    "Panama": "Izzy",
    "Switzerland": "Izzy",
    "Scotland": "Izzy",
}

FLAG_IMG = {
    "Croatia": "https://flagcdn.com/w160/hr.png",
    "Iran": "https://flagcdn.com/w160/ir.png",
    "Germany": "https://flagcdn.com/w160/de.png",
    "Paraguay": "https://flagcdn.com/w160/py.png",
    "South Korea": "https://flagcdn.com/w160/kr.png",
    "Norway": "https://flagcdn.com/w160/no.png",
    "Jordan": "https://flagcdn.com/w160/jo.png",
    "Czechia": "https://flagcdn.com/w160/cz.png",
    "Ecuador": "https://flagcdn.com/w160/ec.png",
    "Colombia": "https://flagcdn.com/w160/co.png",
    "Brazil": "https://flagcdn.com/w160/br.png",
    "Bosnia-Herzegovina": "https://flagcdn.com/w160/ba.png",
    "Austria": "https://flagcdn.com/w160/at.png",
    "Egypt": "https://flagcdn.com/w160/eg.png",
    "Netherlands": "https://flagcdn.com/w160/nl.png",
    "Ghana": "https://flagcdn.com/w160/gh.png",
    "Sweden": "https://flagcdn.com/w160/se.png",
    "Qatar": "https://flagcdn.com/w160/qa.png",
    "Japan": "https://flagcdn.com/w160/jp.png",
    "Congo DR": "https://flagcdn.com/w160/cd.png",
    "United States": "https://flagcdn.com/w160/us.png",
    "Ivory Coast": "https://flagcdn.com/w160/ci.png",
    "Iraq": "https://flagcdn.com/w160/iq.png",
    "Mexico": "https://flagcdn.com/w160/mx.png",
    "Belgium": "https://flagcdn.com/w160/be.png",
    "Canada": "https://flagcdn.com/w160/ca.png",
    "Senegal": "https://flagcdn.com/w160/sn.png",
    "Morocco": "https://flagcdn.com/w160/ma.png",
    "Spain": "https://flagcdn.com/w160/es.png",
    "Turkey": "https://flagcdn.com/w160/tr.png",
    "Tunisia": "https://flagcdn.com/w160/tn.png",
    "Uruguay": "https://flagcdn.com/w160/uy.png",
    "Haiti": "https://flagcdn.com/w160/ht.png",
    "Argentina": "https://flagcdn.com/w160/ar.png",
    "Saudi Arabia": "https://flagcdn.com/w160/sa.png",
    "Cape Verde Islands": "https://flagcdn.com/w160/cv.png",
    "Algeria": "https://flagcdn.com/w160/dz.png",
    "Australia": "https://flagcdn.com/w160/au.png",
    "New Zealand": "https://flagcdn.com/w160/nz.png",
    "Portugal": "https://flagcdn.com/w160/pt.png",
    "Uzbekistan": "https://flagcdn.com/w160/uz.png",
    "England": "https://flagcdn.com/w160/gb-eng.png", #
    "France": "https://flagcdn.com/w160/fr.png",
    "South Africa": "https://flagcdn.com/w160/za.png",
    "Curaçao": "https://flagcdn.com/w160/cw.png",
    "Panama": "https://flagcdn.com/w160/pa.png",
    "Switzerland": "https://flagcdn.com/w160/ch.png",
    "Scotland": "https://flagcdn.com/w160/gb-sct.png",
}