# Team Data
# Team: Player
SWEEPSTAKE = {
    "Croatia": "Oran",
    "Iran": "Oran",
    "Germany": "Oran",
    "Paraguay": "Oran",
    "South Korea": "Swati",
    "Norway": "Swati",
    "Jordan": "Swati",
    "Czechia": "Swati",
    "Ecuador": "Noah",
    "Colombia": "Noah",
    "Brazil": "Noah",
    "Bosnia-Herzegovina": "Noah",
    "Austria": "Aimee",
    "Egypt": "Aimee",
    "Netherlands": "Aimee",
    "Ghana": "Aimee",
    "Sweden": "Kush",
    "Qatar": "Kush",
    "Japan": "Kush",
    "Congo DR": "Kush",
    "United States": "Micky",
    "Ivory Coast": "Micky",
    "Iraq": "Micky",
    "Mexico": "Micky",
    "Belgium": "Mae",
    "Canada": "Mae",
    "Senegal": "Mae",
    "Morocco": "Mae",
    "Spain": "Aden",
    "Turkey": "Aden",
    "Tunisia": "Aden",
    "Uruguay": "Aden",
    "Haiti": "Mary",
    "Argentina": "Mary",
    "Saudi Arabia": "Mary",
    "Cape Verde Islands": "Mary",
    "Algeria": "Will",
    "Australia": "Will",
    "New Zealand": "Will",
    "Portugal": "Will",
    "Uzbekistan": "Joe",
    "England": "Joe",
    "France": "Joe",
    "South Africa": "Joe",
    "Curaçao": "Izzy",
    "Panama": "Izzy",
    "Switzerland": "Izzy",
    "Scotland": "Izzy",
}